---
title: "Anuses"
author: "Elise Navidad"
date: "November 2017 - "
output: html_document
---

```{r Installing Packages, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
options(stringsAsFactors = FALSE)
# install.packages("xts", repos = "http://cran.us.r-project.org")
library(xts)
# install.packages("here", repos = "http://cran.us.r-project.org")
library(here)
# install.packages("zoo", repos = "http://cran.us.r-project.org")
library(zoo)
# install.packages("stringi", repos = "http://cran.us.r-project.org")
library(ggplot2) # for scatterplots
# install.packages("ggeasy", repos = "http://cran.us.r-project.org")
library(ggeasy) # for centering plot titles
# install.packages("scales", repos = "http://cran.us.r-project.org")
library(scales) # for adding commas to numbers without changing to character
# install.packages("dplyr", repos = "http://cran.us.r-project.org")
library(dplyr)
# install.packages("knitr", repos = "http://cran.us.r-project.org")
library(knitr) # for tables (kable function)
# install.packages("openxlsx", repos = "http://cran.us.r-project.org")
library(openxlsx)
# install.packages("data.table", repos = "http://cran.us.r-project.org")
library(data.table)
# install.packages("pander", repos = "http://cran.us.r-project.org")
library(pander)
# install.packages("kableExtra", repos = "http://cran.us.r-project.org")
library(kableExtra)
# install.packages("tibble", repos = "http://cran.us.r-project.org")
library(tibble)
# install.packages("gt", repos = "http://cran.us.r-project.org")
library(gt)
# install.packages("gtExtras", repos = "http://cran.us.r-project.org")
library(gtExtras)
# install.packages("reshape2", repos = "http://cran.us.r-project.org")
library(reshape2)
```

Make sure to knit `Main_Code.Rmd` for the most up-to-date data.

```{r IMPORT: Datanuses, include = FALSE}
here::i_am("Main_Code.Rmd")
Datanuses <- here("Excel", "Datanuses.xlsx")
data_anuses <- read.xlsx(Datanuses, sheet = 1)
data_activity <- read.xlsx(Datanuses, sheet = 2)

# View(data_anuses)

rm(Datanuses)

```

```{r IMPORT, include = TRUE, echo = FALSE}
here::i_am("Anuses.Rmd")
data <- here("Vocs.R")

print("Before")
source(data)
print("After")
```